### ISSUE TITLE
No images generated in pdf-diff output folders

### ISSUE THREAD

**Issue by jrsstill** [serhack/pdf-diff#16]
`user $ pdf-diff a.pdf b.pdf`
```
Color chosen: 255.000000 32.000000 16.000000
Image generation for: a.pdf
[]
Image generation for: b.pdf
[]
```

This creates 2 empty directories named the same as file hash, and one "generated" directory. But all 3 directories are empty.

**Comment by serhack** [comment]
That's weird, are you sure the poppler-utils are installed?

**Comment by jrsstill** [comment]
I think so (installed with pip), but just in case, what is the preferred method to install it?

**Comment by jrsstill** [comment]
Figured it out, I had to re-install poppler.
