### ISSUE TITLE
No image generated

### ISSUE THREAD

**Issue by SergioB-dev** [serhack/pdf-diff#9]
Hi! Very cool project. 

I'm having some problems, I'm hoping you can offer some guidance in case I am doing something wrong.

- So I cloned the project. 
- Downloaded a [dummy pdf](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf).
- Downloaded another dummy pdf and made some edits to it. Saved.
- ran `go run main.go dummy.pdf dummy2.pdf`

### Expected Output

> The images generated by pdf are inserted into a folder named as the hash of the content of the pdf file. E.g. the file has the hash fc324.., the images are in the fc324 folder. If a folder with that name already exists, pdf-diff will not create any images since it consider that images were already generated.
> Once ran, the images are created in the folder generated.

### Actual Output
I got two separate folders with different shas generated, but with no content. Also the generated folder remains empty. 

What am I doing wrong?

**Comment by serhack** [comment]
Hi, thanks for creating a new issue. Have you installed `poppler-utils`? Try to open a new shell and type `pdftoppm`. If there's "no command found" error, probably you need to install it.

For sure I have to find a way to report the lack of `pdftoppm` as an error.

**Comment by SergioB-dev** [comment]
Thanks for the quick reply. You're right. I needed to have that package. I assumed that it came default with brew but it does not. I opened a PR that adds the relevant Mac command to the README.

**Comment by serhack** [comment]
Thank you for the PR. Closing the issue.
